export type DrugCatalogItem = {
  name: string;
  category: string;
  commonForms: string[];
};

export const DRUG_CATALOG: DrugCatalogItem[] = [
  { name: "Abacavir", category: "Antiretroviral", commonForms: ["300mg tablet"] },
  { name: "Albendazole", category: "Anthelmintic", commonForms: ["400mg tablet", "200mg/5ml suspension"] },
  { name: "Amlodipine", category: "Antihypertensive", commonForms: ["5mg tablet", "10mg tablet"] },
  { name: "Amoxicillin", category: "Antibiotic", commonForms: ["250mg capsule", "500mg capsule", "125mg/5ml suspension"] },
  { name: "Amoxicillin/Clavulanic Acid", category: "Antibiotic", commonForms: ["625mg tablet", "457mg/5ml suspension"] },
  { name: "Artemether/Lumefantrine", category: "Antimalarial", commonForms: ["20/120mg tablet"] },
  { name: "Aspirin", category: "Analgesic/Antiplatelet", commonForms: ["75mg tablet", "300mg tablet"] },
  { name: "Atenolol", category: "Antihypertensive", commonForms: ["50mg tablet", "100mg tablet"] },
  { name: "Atorvastatin", category: "Lipid lowering", commonForms: ["10mg tablet", "20mg tablet", "40mg tablet"] },
  { name: "Azithromycin", category: "Antibiotic", commonForms: ["250mg tablet", "500mg tablet", "200mg/5ml suspension"] },
  { name: "Beclomethasone Inhaler", category: "Respiratory", commonForms: ["100mcg inhaler", "200mcg inhaler"] },
  { name: "Benzyl Benzoate", category: "Dermatology", commonForms: ["25% lotion"] },
  { name: "Bisacodyl", category: "Laxative", commonForms: ["5mg tablet", "10mg suppository"] },
  { name: "Captopril", category: "Antihypertensive", commonForms: ["25mg tablet"] },
  { name: "Carbamazepine", category: "Anticonvulsant", commonForms: ["200mg tablet"] },
  { name: "Cefixime", category: "Antibiotic", commonForms: ["200mg tablet", "100mg/5ml suspension"] },
  { name: "Ceftriaxone", category: "Antibiotic", commonForms: ["1g injection"] },
  { name: "Cetirizine", category: "Antihistamine", commonForms: ["10mg tablet", "5mg/5ml syrup"] },
  { name: "Chloramphenicol Eye Drops", category: "Ophthalmic", commonForms: ["0.5% eye drops"] },
  { name: "Ciprofloxacin", category: "Antibiotic", commonForms: ["250mg tablet", "500mg tablet"] },
  { name: "Clarithromycin", category: "Antibiotic", commonForms: ["250mg tablet", "500mg tablet"] },
  { name: "Clotrimazole", category: "Antifungal", commonForms: ["1% cream", "100mg pessary"] },
  { name: "Co-trimoxazole", category: "Antibiotic", commonForms: ["480mg tablet", "960mg tablet", "240mg/5ml suspension"] },
  { name: "Dexamethasone", category: "Corticosteroid", commonForms: ["4mg tablet", "4mg/ml injection"] },
  { name: "Diclofenac", category: "NSAID", commonForms: ["50mg tablet", "75mg injection", "1% gel"] },
  { name: "Doxycycline", category: "Antibiotic", commonForms: ["100mg capsule"] },
  { name: "Enalapril", category: "Antihypertensive", commonForms: ["5mg tablet", "10mg tablet"] },
  { name: "Erythromycin", category: "Antibiotic", commonForms: ["250mg tablet", "125mg/5ml suspension"] },
  { name: "Ferrous Sulphate", category: "Haematinic", commonForms: ["200mg tablet", "syrup"] },
  { name: "Fluconazole", category: "Antifungal", commonForms: ["150mg capsule", "200mg capsule"] },
  { name: "Folic Acid", category: "Vitamin", commonForms: ["5mg tablet"] },
  { name: "Furosemide", category: "Diuretic", commonForms: ["40mg tablet", "20mg/2ml injection"] },
  { name: "Gentamicin", category: "Antibiotic", commonForms: ["40mg/ml injection", "0.3% eye drops"] },
  { name: "Glibenclamide", category: "Antidiabetic", commonForms: ["5mg tablet"] },
  { name: "Hydrochlorothiazide", category: "Diuretic", commonForms: ["25mg tablet"] },
  { name: "Hydrocortisone", category: "Corticosteroid", commonForms: ["1% cream", "100mg injection"] },
  { name: "Ibuprofen", category: "NSAID", commonForms: ["200mg tablet", "400mg tablet", "100mg/5ml suspension"] },
  { name: "Insulin Regular", category: "Antidiabetic", commonForms: ["100IU/ml injection"] },
  { name: "Lactulose", category: "Laxative", commonForms: ["3.35g/5ml syrup"] },
  { name: "Lamivudine", category: "Antiretroviral", commonForms: ["150mg tablet"] },
  { name: "Lansoprazole", category: "Gastrointestinal", commonForms: ["30mg capsule"] },
  { name: "Levocetirizine", category: "Antihistamine", commonForms: ["5mg tablet"] },
  { name: "Loperamide", category: "Antidiarrhoeal", commonForms: ["2mg capsule"] },
  { name: "Loratadine", category: "Antihistamine", commonForms: ["10mg tablet", "5mg/5ml syrup"] },
  { name: "Losartan", category: "Antihypertensive", commonForms: ["50mg tablet", "100mg tablet"] },
  { name: "Magnesium Trisilicate", category: "Antacid", commonForms: ["tablet", "suspension"] },
  { name: "Mebendazole", category: "Anthelmintic", commonForms: ["100mg tablet", "500mg tablet"] },
  { name: "Metformin", category: "Antidiabetic", commonForms: ["500mg tablet", "850mg tablet"] },
  { name: "Metoclopramide", category: "Antiemetic", commonForms: ["10mg tablet", "5mg/ml injection"] },
  { name: "Metronidazole", category: "Antibiotic/Antiprotozoal", commonForms: ["200mg tablet", "400mg tablet", "200mg/5ml suspension"] },
  { name: "Miconazole", category: "Antifungal", commonForms: ["2% cream", "oral gel"] },
  { name: "Montelukast", category: "Respiratory", commonForms: ["5mg tablet", "10mg tablet"] },
  { name: "Nifedipine", category: "Antihypertensive", commonForms: ["20mg tablet"] },
  { name: "Omeprazole", category: "Gastrointestinal", commonForms: ["20mg capsule", "40mg capsule"] },
  { name: "Ondansetron", category: "Antiemetic", commonForms: ["4mg tablet", "4mg/2ml injection"] },
  { name: "Oral Rehydration Salts", category: "Rehydration", commonForms: ["sachet"] },
  { name: "Paracetamol", category: "Analgesic/Antipyretic", commonForms: ["500mg tablet", "120mg/5ml syrup", "250mg suppository"] },
  { name: "Penicillin V", category: "Antibiotic", commonForms: ["250mg tablet"] },
  { name: "Prednisolone", category: "Corticosteroid", commonForms: ["5mg tablet"] },
  { name: "Promethazine", category: "Antihistamine", commonForms: ["25mg tablet", "5mg/5ml syrup"] },
  { name: "Salbutamol Inhaler", category: "Respiratory", commonForms: ["100mcg inhaler"] },
  { name: "Salbutamol Syrup", category: "Respiratory", commonForms: ["2mg/5ml syrup"] },
  { name: "Simvastatin", category: "Lipid lowering", commonForms: ["20mg tablet", "40mg tablet"] },
  { name: "Tinidazole", category: "Antiprotozoal", commonForms: ["500mg tablet"] },
  { name: "Vitamin B Complex", category: "Vitamin", commonForms: ["tablet", "syrup"] },
  { name: "Vitamin C", category: "Vitamin", commonForms: ["500mg tablet", "syrup"] },
  { name: "Zinc Sulphate", category: "Supplement", commonForms: ["20mg tablet", "10mg/5ml syrup"] },
];
